AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Parameters:
  QueueDelaySecondsParameter:
    Default: 0
    Type: Number
  QueueMessageRetentionPeriodParameter:
    Default: 345600
    Type: Number
  QueueVisibilityTimeoutParameter:
    Default: 30
    Type: Number
  ScheduleProducerPeriodicityParameter:
    Default: "rate(2 minutes)"
    Type: String

Resources:
  MyQueue:
    Type: AWS::SQS::Queue
    Properties: 
      DelaySeconds:
        Ref: QueueDelaySecondsParameter
      MessageRetentionPeriod: 
        Ref: QueueMessageRetentionPeriodParameter
      QueueName: MyQueue
      ReceiveMessageWaitTimeSeconds: 0
#      RedriveAllowPolicy: Json
#      RedrivePolicy: Json
      VisibilityTimeout: 
        Ref: QueueVisibilityTimeoutParameter

  MyTable:
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions:
        - AttributeName: "DateTime"
          AttributeType: "S"
      BillingMode: "PAY_PER_REQUEST"
      KeySchema:
        - AttributeName: "DateTime"
          KeyType: "HASH"
      TableName: Sums
      TimeToLiveSpecification:
        AttributeName: "ttl"
        Enabled: true

  # Event Bridges
  scheduleProducerLambda:
    DependsOn: [LambdaProducer]
    Type: AWS::Events::Rule
    Properties:
      Description: 'This is the trigger for the producer lambda'
      ScheduleExpression:
        Ref: ScheduleProducerPeriodicityParameter
      State: ENABLED
      Targets: 
        -
          Arn: !GetAtt LambdaProducer.Arn
          Id: 1234IDeclareAEBWar

  # Lambdas
  LambdaProducer:
    Type: AWS::Serverless::Function
    DependsOn: LambdaServiceRole
    Properties:
      Handler: producer.lambda_handler
      CodeUri: . 
      Description: 'The producer function'
      MemorySize: 256
      Timeout: 5
      Role: !GetAtt LambdaServiceRole.Arn
      Runtime: python3.9

  LambdaConsumer:
    Type: AWS::Serverless::Function
    DependsOn: LambdaServiceRole
    Properties:
      Handler: consumer.lambda_handler
      CodeUri: . 
      Description: 'The consumer function'
      Events:
        # https://aws.amazon.com/blogs/aws/aws-lambda-adds-amazon-simple-queue-service-to-supported-event-sources/?utm_source=feedburner&utm_medium=feed&utm_campaign=Feed%3A+AmazonWebServicesBlog+%28Amazon+Web+Services+Blog%29
        # Attempt to use a direct Event binding, rather than Eventbridge.
        MySQSEvent:
          Type: "SQS"
          Properties:
            BatchSize: 1
            Queue: !GetAtt MyQueue.Arn
      MemorySize: 256
      Timeout: 5
      Role: !GetAtt LambdaServiceRole.Arn
      Runtime: python3.9

  PermissionForEventsToInvokeProducerLambda: 
    DependsOn: [LambdaProducer]
    Type: AWS::Lambda::Permission
    Properties: 
      FunctionName: 
        Ref: "LambdaProducer"
      Action: "lambda:InvokeFunction"
      Principal: "events.amazonaws.com"
      SourceArn:
        Fn::GetAtt: 
          - "scheduleProducerLambda"
          - "Arn"

  # Roles
  LambdaServiceRole:
    Type:  AWS::IAM::Role
    Properties:
      RoleName: LambdaServiceRole
      Description: Allows Lambda functions to call DyDB, SQS.
      Path: /
      # Unsure what this does?
      # https://devops.stackexchange.com/questions/5094/what-is-the-purpose-of-assumerolepolicydocument-in-iam/5099
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: [lambda.amazonaws.com]
            Action: sts:AssumeRole
      Policies:
        - PolicyName: SNSRolePolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'sqs:*'
                  - 'dynamodb:*'
                Resource: '*'
      ManagedPolicyArns:
        - !Ref AWSLambdaBasicExecutionRole # Important. Gives Lambda perms to write to CWatch.

        


