# TODO: remove, as this is no longer required.

# Start from a AWS-provided public Python image.
FROM public.ecr.aws/docker/library/python:3.11-slim

# Install ffmpeg
RUN apt-get update && apt-get install -y ffmpeg curl && rm -rf /var/lib/apt/lists/*

# Install yt-dlp
RUN pip install --upgrade yt-dlp openai tiktoken python-dotenv rich pydantic boto3

# Copy your pipeline code
WORKDIR /app

# Should take ~8 mins to build.