# Start from the prior base image.
FROM 177738943897.dkr.ecr.ap-southeast-2.amazonaws.com/reinvent-pipeline-base:latest 
# ^^ TODO: parameterize.

# Install ffmpeg
#RUN apt-get update && apt-get install -y ffmpeg curl && rm -rf /var/lib/apt/lists/*

# Install yt-dlp
#RUN pip install --upgrade yt-dlp openai tiktoken python-dotenv rich pydantic

# Copy your pipeline code
#WORKDIR /app
COPY pipeline /app/pipeline
COPY runVideoPipeline.py /app/runVideoPipeline.py

ENV PYTHONPATH=/app

ENTRYPOINT ["python", "runVideoPipeline.py"]

# Should take < 1 min to build.