version: 0.2

env:
  variables:
    IMAGE_NAME: reinvent-pipeline-base
    ECR_REPO: 177738943897.dkr.ecr.ap-southeast-2.amazonaws.com/reinvent-pipeline-base:latest
    IMAGE_TAG: latest

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REPO
      - echo Build started on `date`
  build:
    commands:
      - echo Building the Docker image for ARM64...
      - docker buildx create --use || true
      - docker buildx build --platform linux/arm64 --build-arg DEBIAN_FRONTEND=noninteractive --file Dockerfile-base -t $ECR_REPO:$IMAGE_TAG --push reinvent_pipeline-base/
      - echo Build completed.
  post_build:
    commands:
#      - echo Pushing the Docker image to ECR...
#      - docker tag $ECR_REPO:$IMAGE_TAG $ECR_REPO:$IMAGE_TAG
#      - docker push $ECR_REPO:$IMAGE_TAG
#      - echo Pushed successfully
